# Generated by Django 2.0.2 on 2019-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('c_password', models.IntegerField()),
                ('c_name', models.CharField(max_length=20)),
                ('c_phone_no', models.IntegerField()),
                ('c_email_id', models.EmailField(max_length=20)),
                ('c_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_password', models.IntegerField()),
                ('t_name', models.CharField(max_length=20)),
                ('t_phone_no', models.IntegerField()),
                ('t_email', models.CharField(max_length=20)),
                ('t_type', models.CharField(max_length=15)),
                ('t_location', models.CharField(max_length=20)),
                ('t_rupee', models.IntegerField()),
                ('t_address', models.CharField(max_length=50)),
            ],
        ),
    ]
