# Generated by Django 2.0.2 on 2019-01-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtoZdelivery', '0003_auto_20190120_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_id',
        ),
    ]
